Update draft_all.py
Fix to bug:
Traceback (most recent call last):
  File "/datacnmat01/ingenieria/usuarios/ariel.posada/dnn_all.py", line 101, in <module>
    critic_learner.load(f'/home/ariel.posada/data/out/gan_trained_{sufijo}_{current_time}', with_opt=False)
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/learner.py", line 420, in load
    load_model(file, self.model, self.opt, device=device, **kwargs)
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/learner.py", line 54, in load_model
    get_model(model).load_state_dict(model_state, strict=strict)
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CustomCritic:
        Missing key(s) in state_dict: "conv_layers.0.0.weight", "conv_layers.1.0.0.weight", "conv_layers.1.0.1.weight", "conv_layers.1.0.1.bias", "conv_layer
s.1.0.1.running_mean", "conv_layers.1.0.1.running_var", "conv_layers.1.1.0.weight", "conv_layers.1.1.1.weight", "conv_layers.1.1.1.bias", "conv_layers.1.1.1.
running_mean", "conv_layers.1.1.1.running_var", "conv_layers.2.0.0.weight", "conv_layers.2.0.1.weight", "conv_layers.2.0.1.bias", "conv_layers.2.0.1.running_
mean", "conv_layers.2.0.1.running_var", "conv_layers.3.0.0.weight", "conv_layers.3.0.1.weight", "conv_layers.3.0.1.bias", "conv_layers.3.0.1.running_mean", "
conv_layers.3.0.1.running_var", "conv_layers.4.0.weight", "fc.weight", "fc.bias".
        Unexpected key(s) in state_dict: "generator.1.0.weight", "generator.1.1.weight", "generator.1.1.bias", "generator.1.1.running_mean", "generator.1.1.r
unning_var", "generator.1.1.num_batches_tracked", "generator.2.0.weight", "generator.2.1.weight", "generator.2.1.bias", "generator.2.1.running_mean", "genera
tor.2.1.running_var", "generator.2.1.num_batches_tracked", "generator.3.0.weight", "generator.3.1.weight", "generator.3.1.bias", "generator.3.1.running_mean"
, "generator.3.1.running_var", "generator.3.1.num_batches_tracked", "generator.4.0.weight", "generator.4.1.weight", "generator.4.1.bias", "generator.4.1.runn
ing_mean", "generator.4.1.running_var", "generator.4.1.num_batches_tracked", "generator.5.0.weight", "generator.5.1.weight", "generator.5.1.bias", "generator
.5.1.running_mean", "generator.5.1.running_var", "generator.5.1.num_batches_tracked", "generator.6.0.weight", "generator.6.1.weight", "generator.6.1.bias", "
generator.6.1.running_mean", "generator.6.1.running_var", "generator.6.1.num_batches_tracked", "generator.7.0.weight", "generator.7.1.weight", "generator.7.1
.bias", "generator.7.1.running_mean", "generator.7.1.running_var", "generator.7.1.num_batches_tracked", "generator.8.weight", "critic.conv_layers.0.0.weight"
, "critic.conv_layers.1.0.0.weight", "critic.conv_layers.1.0.1.weight", "critic.conv_layers.1.0.1.bias", "critic.conv_layers.1.0.1.running_mean", "critic.con
v_layers.1.0.1.running_var", "critic.conv_layers.1.0.1.num_batches_tracked", "critic.conv_layers.1.1.0.weight", "critic.conv_layers.1.1.1.weight", "critic.co
nv_layers.1.1.1.bias", "critic.conv_layers.1.1.1.running_mean", "critic.conv_layers.1.1.1.running_var", "critic.conv_layers.1.1.1.num_batches_tracked", "crit
ic.conv_layers.2.0.0.weight", "critic.conv_layers.2.0.1.weight", "critic.conv_layers.2.0.1.bias", "critic.conv_layers.2.0.1.running_mean", "critic.conv_layer
s.2.0.1.running_var", "critic.conv_layers.2.0.1.num_batches_tracked", "critic.conv_layers.3.0.0.weight", "critic.conv_layers.3.0.1.weight", "critic.conv_laye
rs.3.0.1.bias", "critic.conv_layers.3.0.1.running_mean", "critic.conv_layers.3.0.1.running_var", "critic.conv_layers.3.0.1.num_batches_tracked", "critic.conv
_layers.4.0.weight", "critic.fc.weight", "critic.fc.bias".