Update draft_updated_all.py
Fix:

Traceback (most recent call last):
  File "/datacnmat01/ingenieria/usuarios/ariel.posada/dnn_all.py", line 189, in <module>
    train_generator(dls, generator, discriminator, optimizer_g)
  File "/datacnmat01/ingenieria/usuarios/ariel.posada/dnn_all.py", line 160, in train_generator
    loss.backward()
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/torch/_tensor.py", line 478, in backward
    return handle_torch_function(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/torch/overrides.py", line 1551, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/torch_core.py", line 382, in __torch_function__
    res = super().__torch_function__(func, types, args, ifnone(kwargs, {}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/torch/_tensor.py", line 1295, in __torch_function__
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn