Update draft_updated_all.py
Fix:

[ariel.posada@caldas01 data]$ more slurm.thanatos-1-6.257747.err
/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/data/transforms.py:225: FutureWarning: is_categorical_dtype is deprecated
and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(col):
Traceback (most recent call last):
  File "/datacnmat01/ingenieria/usuarios/ariel.posada/dnn_all.py", line 231, in <module>
    train_discriminator_for_one_epoch(dls, discriminator, optimizer_d)
  File "/datacnmat01/ingenieria/usuarios/ariel.posada/dnn_all.py", line 214, in train_discriminator_for_one_epoch
    real_pred = discriminator(real_images, labels)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/datacnmat01/ingenieria/usuarios/ariel.posada/dnn_all.py", line 155, in forward
    images = torch.cat([images, label_conditioning], 1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: no implementation found for 'torch.cat' on types that implement __torch_function__: [<class 'fastai.torch_core.TensorImage'>, <class 'fastai.torch
_core.TensorCategory'>]