Update draft_updated_all.py
Fix

Traceback (most recent call last):
  File "/datacnmat01/ingenieria/usuarios/ariel.posada/dnn_all.py", line 175, in <module>
    learn_gen.fit_one_cycle(5, slice(1e-6,1e-3))
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/callback/schedule.py", line 119, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd, start_epoch=start_epoch)
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/learner.py", line 264, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
                                        ^^^
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/learner.py", line 253, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
                                        ^^^
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/learner.py", line 247, in _do_epoch
    self._do_epoch_train()
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/learner.py", line 239, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
                                        ^^^
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/fastai/learner.py", line 205, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
                                 ^^^^^^^^^^^^^^^^^^
  File "/datacnmat01/ingenieria/usuarios/ariel.posada/dnn_all.py", line 153, in one_batch
    self.pred = self.model(noise)
                ^^^^^^^^^^^^^^^^^
  File "/datacnmat01/ciencias/appsbio/conda/envs/AFGIE/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConditionalGenerator.forward() missing 1 required positional argument: 'labels'